"""add recommend columns to papers

Revision ID: 0de46d2c390a
Revises: 8ffb22fe7333
Create Date: 2026-07-02 10:45:30.101911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de46d2c390a'
down_revision: Union[str, None] = '8ffb22fe7333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('is_recommended', sa.Boolean(), nullable=True))
    op.add_column('papers', sa.Column('recommend_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'recommend_order')
    op.drop_column('papers', 'is_recommended')
    # ### end Alembic commands ###
